### ISSUE TITLE
Please confirm new stepper microsteps values

### ISSUE THREAD

**Issue by nicwilson58** [qidi-community/Plus4-Wiki#11]
I am altering my stepper values as you suggested but would like to clarify the stepper_z and stepper_z1

The x and y stepper microsteps were 32 and I have raised them to 64

however my two z values as installed  by firmware 1.43 are both set to 128,  can you please confirm dropping them to 32 as noted in your example.

**Comment by stew675** [comment]
Yes, the 32 was intentional.

The Z lead screws have a 4mm thread pitch, meaning the bed travels 4mm for 1 full rotation.

The Z steppers have 200 full steps per full rotation.

The stock config allowed for 128 micro-steps per full step.

Running the math, the size of each micro-step was :  (4.0mm / 200) / 128 ~= 0.00016mm, or 0.16 microns.

That level of resolution simply isn't necessary on the Z axis, nor is it even achievable (with repeatable accuracy) in practice.  The move to 32 steps results in more positionally accurate motions (in a real sense, as opposed to on paper), and at a 0.6 micron resolution, which is still way more than necessary, but it does free up some processing overhead on the MCU to allow it to spend that processing power on better accuracy with the X/Y motions.
